name: Test

on: push


#    strategy:
#      matrix:
#        python-version: [3.7, 3.8]
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install numpy
#    - name: Simple Test
#      run: |
#        python main.py

jobs:
  container:
    runs-on: ubuntu-latest
#    container: jupyter/pyspark-notebook
    container: jupyter/pyspark-notebook:f646d2b2a3af
    steps:
      - name: Install dependencies
      - run: |
          echo "This job does specify a container."
          echo "It runs in the container instead of the VM."
          python -V
          pyspark --version
          python -m pip install pybind11 pytest
          export PYTHONPATH="${SPARK_HOME}/python/:$PYTHONPATH"
          export PYTHONPATH="${SPARK_HOME}/python/lib/py4j-0.10.9-src.zip:$PYTHONPATH"
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install default-jdk -y
          apt-get install -y gnupg2 gnupg gnupg1
          wget www.scala-lang.org/files/archive/scala-2.13.0.deb
          sudo dpkg -i scala*.deb
          echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
          sudo apt-get update
          sudo apt-get install sbt -y


      - name: Test
      - run: |
          sbt test


#
#jobs:
#  vm:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          echo This job does not specify a container.
#          echo It runs directly on the virtual machine.
#        name: Run on VM
#  container:
#    runs-on: ubuntu-latest
#    container: node:10.16-jessie
#    steps:
#      - run: |
#          echo This job does specify a container.
#          echo It runs in the container instead of the VM.
#        name: Run in container




